---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```
This R package contains data and R code from the forthcoming book provisionally entitled "Bayesian Regression with INLA". It is not ready for public use.

You can install it (provided you have loaded the `devtools` package) with:

```{r eval=FALSE}
install_github(“julianfaraway/brinla”)
```

Functions and data available are:

```
Index:

BayesLM.nprior                      Bayes Linear Model
bri.density.summary                 Compute a summary from a density
bri.fixed.plot                      Plot posterior densities of the fixed effects
bri.hyper.sd                        Convert precision to SD
bri.hyperpar.plot                   Plot the hyperparameter posteriors
bri.hyperpar.summary                Convert precisions to SD in INLA hyperparameter summary
bri.random.plot                     Plot the posterior densities of the random effects
fossil                              Strontium content of fossils
hubble                              Hubble Space Telescope Data
kyphosis                            Children who have had Corrective Spinal Surgery
ohio                                Ohio Children Wheeze Status
reading                             Reading scores in school children
reeds                               Fowlmere reeds data
usair                               US Air Pollution
```

