---
title: "Script for glmm"
author: "Bayesian Regression with INLA author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{glmm script}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
data(reeds, package="brinla")
summary(reeds)
```
```{r}
library(lme4)
mmod <- lmer(nitrogen ~ 1+(1|site), reeds)
summary(mmod)
```
```{r}
library(INLA)
formula <- nitrogen ~ 1 + f(site, model="iid")
imod <- inla(formula,family="gaussian", data = reeds)
summary(imod)
```
```{r}
invsqrt <- function(x) 1/sqrt(x)
sdt <- invsqrt(imod$summary.hyperpar[,-2])
row.names(sdt) <- c("SD of epsilson","SD of site")
sdt
```
```{r}
prec.site <- imod$marginals.hyperpar$"Precision for site"
prec.epsilon <- imod$marginals.hyperpar$"Precision for the Gaussian observations"
c(epsilon=inla.emarginal(invsqrt,prec.epsilon),site=inla.emarginal(invsqrt,prec.site))
```
```{r}
sigma.site <- inla.tmarginal(invsqrt, prec.site)
sigma.epsilon <- inla.tmarginal(invsqrt, prec.epsilon)
c(epsilon=inla.mmarginal(sigma.epsilon),site=inla.mmarginal(sigma.site))
```
```{r}
inla.contrib.sd(imod)$hyper
```
```{r}
sampvars <- 1/inla.hyperpar.sample(1000,imod)
sampicc <- sampvars[,2]/(rowSums(sampvars))
quantile(sampicc, c(0.025,0.5,0.975))
```
```{r}
library(brinla)
bri.hyperpar.summary(imod)
```
```{r}
alpha <- data.frame(imod$marginals.fixed[[1]])
library(ggplot2)
ggplot(alpha, aes(x,y)) + geom_line() + xlim(2,4) + geom_vline(xintercept = c(2.66, 3.40))+xlab("nitrogen")+ylab("density")
```
```{r}
x <- seq(0,1,len=100)
d1 <- inla.dmarginal(x,sigma.site)
d2 <- inla.dmarginal(x,sigma.epsilon)
rdf <- data.frame(nitrogen=c(x,x),sigma=gl(2,100,labels=c("site","epsilon")),density=c(d1,d2))
ggplot(rdf, aes(x=nitrogen, y=density, linetype=sigma))+geom_line()
```
```{r}
bri.hyperpar.plot(imod)
```
```{r}
sdres <- sd(reeds$nitrogen)
pcprior <- list(prec = list(prior="pc.prec", param = c(3*sdres,0.01)))
formula <- nitrogen ~ f(site, model="iid", hyper = pcprior)
imod <- inla(formula, family="gaussian", data=reeds)
```
```{r}
imod$summary.fixed
```
```{r}
bri.hyperpar.summary(imod)
```
```{r}
bri.hyperpar.plot(imod)
```
```{r}
reff <- imod$marginals.random
x <- seq(-1.5,1.5,len=100)
d1 <- inla.dmarginal(x, reff$site[[1]])
d2 <- inla.dmarginal(x, reff$site[[2]])
d3 <- inla.dmarginal(x, reff$site[[3]])
rdf <- data.frame(nitrogen=x,density=c(d1,d2,d3),site=gl(3,100,labels=LETTERS[1:4]))
ggplot(rdf, aes(x=nitrogen, y=density, linetype=site))+geom_line()
```
```{r}
bri.random.plot(imod)
```
```{r}
imod <- inla(formula, family="gaussian", data=reeds, control.compute=list(config = TRUE))
psamp <- inla.posterior.sample(n=1000, imod)
psamp[[1]]
```
```{r}
lvsamp <- t(sapply(psamp, function(x) x$latent))
colnames(lvsamp) <- row.names(psamp[[1]]$latent)
mean(lvsamp[,'site:C'] > lvsamp[,'site:A'])
```
```{r}
data(reading, package="brinla")
ggplot(reading, aes(agegrp, piat, group=id)) + geom_line()
```
```{r}
library(lme4)
lmod <- lmer(piat ~ agegrp + (1|id), reading)
summary(lmod)
```
```{r}
formula <- piat ~ agegrp + f(id, model="iid")
imod <- inla(formula, family="gaussian", data=reading)
```
```{r}
imod$summary.fixed
```
```{r}
bri.hyperpar.summary(imod)
```
```{r}
bri.hyperpar.plot(imod)
```
```{r}
summary(imod$summary.random$id$mean)
```
```{r}
bri.random.plot(imod)
```
```{r}
reading$cagegrp <- reading$agegrp - 8.5
lmod <- lmer(piat ~ cagegrp + (cagegrp|id), reading)
summary(lmod)
```
```{r}
nid <- length(levels(reading$id))
reading$numid <- as.numeric(reading$id)
reading$slopeid <- reading$numid + nid
```
```{r}
formula <- piat ~ cagegrp + f(numid, model="iid2d", n = 2*nid) + f(slopeid, cagegrp, copy="numid")
imod <- inla(formula, family="gaussian", data=reading)
```
```{r}
imod$summary.fixed
```
```{r}
bri.hyperpar.summary(imod)
```
```{r}
postmean <- matrix(imod$summary.random$numid[,2],nid,2)
postmean <- sweep(postmean,2,imod$summary.fixed$mean,"+")
p=ggplot(reading, aes(cagegrp, piat, group=id)) + geom_line(col=gray(0.95)) + xlab("centered age")
p+geom_abline(data=postmean,intercept=postmean[,1],slope=postmean[,2])
```
```{r}
library(gridExtra)
sd.epsilon <- bri.hyper.sd(imod$internal.marginals.hyperpar[[1]],internal=TRUE)
sd.intercept <- bri.hyper.sd(imod$internal.marginals.hyperpar[[2]],internal=TRUE)
sd.slope <- bri.hyper.sd(imod$internal.marginals.hyperpar[[3]],internal=TRUE)
p1=ggplot(data.frame(sd.epsilon),aes(x,y))+geom_line()+ggtitle("Epsilon")+xlab("piat")+ylab("density")
p2=ggplot(data.frame(sd.intercept),aes(x,y))+geom_line()+ggtitle("Intercept")+xlab("piat")+ylab("density")
p3=ggplot(data.frame(sd.slope),aes(x,y))+geom_line()+ggtitle("Slope")+xlab("piat")+ylab("density")
p4=ggplot(data.frame(imod$marginals.hyperpar[[4]]),aes(x,y))+geom_line()+ggtitle("Rho")+ylab("density")
grid.arrange(p1,p2,p3,p4,ncol=2)
```
```{r}
bri.hyperpar.plot(imod, together=FALSE)
```
```{r}
formula <- log(piat) ~ cagegrp + f(numid, model="iid2d", n = 2*nid) + f(slopeid, cagegrp, copy="numid")
imod <- inla(formula, family="gaussian", data=reading)
bri.density.summary(imod$marginals.hyperpar[[4]])
```
```{r}
data(reading, package="brinla")
reading$id <- as.numeric(reading$id)
newsub <- data.frame(id=90, agegrp = c(6.5,8.5,10.5), piat=c(18, 25, NA))
nreading <- rbind(reading, newsub)
```
```{r}
formula <- piat ~ agegrp + f(id, model="iid")
imod <- inla(formula, family="gaussian", data=nreading, control.predictor = list(compute=TRUE))
pm90 <- imod$marginals.fitted.values[[270]]
p1 <- ggplot(data.frame(pm90),aes(x,y))+geom_line()+xlim(c(20,60))
```
```{r}
newsub=data.frame(id=90, agegrp = c(6.5,8.5,10.5), piat=c(NA, NA, NA))
nreading <- rbind(reading, newsub)
```
```{r}
formula <- piat ~ agegrp + f(id, model="iid")
imodq <- inla(formula, family="gaussian", data=nreading, control.predictor = list(compute=TRUE))
qm90 <- imodq$marginals.fitted.values[[270]]
p1+geom_line(data=data.frame(qm90),aes(x,y),linetype=2)+xlab("PIAT")+ylab("density")
```
```{r}
nsamp <- 10000
randprec <- inla.hyperpar.sample(nsamp, imod)[,1]
neweps <- rnorm(nsamp, mean=0, sd=1/sqrt(randprec))
newobs <- inla.rmarginal(nsamp, pm90) + neweps
dens <- density(newobs)
p1 + geom_line(data=data.frame(x=dens$x,y=dens$y),aes(x,y),linetype=2)
```
```{r}
data(nitrofen, package="boot")
head(nitrofen)
```
```{r}
library(dplyr)
library(tidyr)
lnitrofen <- select(nitrofen, -total) %>% mutate(id=1:nrow(nitrofen)) %>% gather(brood,live,-conc,-id) %>% arrange(id)
lnitrofen$brood <- factor(lnitrofen$brood,labels=1:3)
head(lnitrofen)
```
```{r}
lnitrofen$jconc <- lnitrofen$conc + rep(c(-10,0,10),50)
ggplot(lnitrofen, aes(x=jconc,y=live, shape=brood)) + geom_point(position = position_jitter(w = 0, h = 0.5)) + xlab("Concentration")
```
```{r}
library(lme4)
glmod <- glmer(live ~ I(conc/300)*brood + (1|id), nAGQ=25, family=poisson, data=lnitrofen)
summary(glmod)
```
```{r}
formula <- live ~ I(conc/300)*brood + f(id, model="iid")
imod <- inla(formula, family="poisson", data=lnitrofen)
```
```{r}
imod$summary.fixed
```
```{r}
bri.hyperpar.summary(imod)
```
```{r}
library(reshape2)
mf <- melt(imod$marginals.fixed)
cf <- spread(mf,Var2,value)
names(cf)[2] = 'parameter'
ggplot(cf,aes(x=x,y=y))+geom_line()+facet_wrap(~ parameter, scales="free")+geom_vline(xintercept=0)+ylab("density")
```
```{r}
bri.fixed.plot(imod)
```
```{r}
bri.fixed.plot(imod,together=TRUE)
```
```{r}
multeff <- exp(imod$summary.fixed$mean)
names(multeff) <- imod$names.fixed
multeff[-1]
```
```{r}
sden <- data.frame(bri.hyper.sd(imod$marginals.hyperpar[[1]]))
ggplot(sden,aes(x,y)) + geom_line() + ylab("density") + xlab("linear predictor")
```
```{r}
bri.hyperpar.plot(imod)
```
```{r}
mden <- data.frame(inla.tmarginal(function(x) exp(1/sqrt(x)), imod$marginals.hyperpar[[1]]))
ggplot(mden,aes(x,y)) + geom_line() + ylab("density") + xlab("multiplicative")
```
```{r}
formula <- live ~ I(conc/300)*brood + f(id, model="iid")
imod <- inla(formula, family="poisson", data=lnitrofen, control.compute=list(dic=TRUE))
formula = live ~ log(conc+1)*brood + f(id, model="iid")
imod2 = inla(formula, family="poisson", data=lnitrofen, control.compute=list(dic=TRUE))
c(imod$dic$dic,  imod2$dic$dic)
```
```{r}
mreff <- imod$summary.random$id$mean
qqnorm(mreff)
qqline(mreff)
```
```{r}
formula <- live ~ I(conc/300)*brood + f(id, model="iid")
imod <- inla(formula, family="poisson", data=lnitrofen, control.compute=list(cpo=TRUE))
plot(log(imod$cpo$cpo),ylab="log(CPO)")
```
```{r}
lnitrofen[which.min(imod$cpo$cpo),]
```
```{r}
lnitrofen %>% filter(brood == 2, conc==310)
```
```{r}
pit <- imod$cpo$pit
n <- length(pit)
uniquant <- (1:n)/(n+1)
logit <- function(p) log(p/(1-p))
plot(logit(uniquant), logit(sort(pit)), xlab="uniform quantiles", ylab="Sorted PIT values")
abline(0,1)
```
```{r}
which.max(pit)
```
```{r}
sdu <- 0.3
pcprior <- list(prec = list(prior="pc.prec", param = c(3*sdu,0.01)))
formula = live ~ I(conc/300)*brood + f(id, model="iid", hyper = pcprior)
imod2 = inla(formula, family="poisson", data=lnitrofen)
bri.hyperpar.summary(imod2)
```
```{r}
lnitrofen$obsid = 1:nrow(nitrofen)
formula <- live ~ I(conc/300)*brood + f(id, model="iid") + f(obsid, model="iid")
imodo <- inla(formula, family="poisson", data=lnitrofen)
bri.hyperpar.summary(imodo)
```
```{r}
data(ohio, package="brinla")
table(ohio$smoke)/4
```
```{r}
xtabs(resp ~ smoke + age, ohio)/c(350,187)
```
```{r}
library(lme4)
modagh <- glmer(resp ~ age + smoke + (1|id), nAGQ=25, family=binomial, data=ohio)
summary(modagh)
```
```{r}
formula <- resp ~ age + smoke + f(id, model="iid")
imod <- inla(formula, family="binomial", data=ohio)
```
```{r}
imod$summary.fixed
```
```{r}
ilogit <- function(x) exp(x)/(1 + exp(x))
ilogit(imod$summary.fixed[1,c(3,4,5)])
```
```{r}
exp(imod$summary.fixed[-1, c(3,4,5)])
```
```{r}
bri.hyperpar.summary(imod)
```
```{r}
exp(bri.hyperpar.summary(imod)[3:5])
```
```{r}
table(xtabs(resp ~ id, ohio))
```
```{r}
library(gridExtra)
p1 <- ggplot(data.frame(imod$marginals.fixed[[1]]),aes(x,y))+geom_line()+xlab("logit")+ylab("density")+ggtitle("Intercept")
p2 <- ggplot(data.frame(imod$marginals.fixed[[2]]),aes(x,y))+geom_line()+xlab("logit")+ylab("density")+ggtitle("age")
p3 <- ggplot(data.frame(imod$marginals.fixed[[3]]),aes(x,y))+geom_line()+xlab("logit")+ylab("density")+ggtitle("smoke")
sden <- data.frame(bri.hyper.sd(imod$marginals.hyperpar[[1]]))
p4 <- ggplot(sden,aes(x,y)) + geom_line() + xlab("logit") + ylab("density")+ggtitle("SD(u)")
grid.arrange(p1,p2,p3,p4,ncol=2)
```
```{r}
inla.pmarginal(0,imod$marginals.fixed$smoke)
```
```{r}
formula <- resp ~ age + smoke + f(id, model="iid")
imod <- inla(formula, family="binomial", data=ohio, control.compute=list(dic=TRUE,waic=TRUE))
formula <- resp ~ factor(age) + smoke + f(id, model="iid")
imod1 <- inla(formula, family="binomial", data=ohio, control.compute=list(dic=TRUE,waic=TRUE))
formula <- resp ~ factor(age)*smoke + f(id, model="iid")
imod2 <- inla(formula, family="binomial", data=ohio, control.compute=list(dic=TRUE,waic=TRUE))
```
```{r}
c(imod$dic$dic, imod1$dic$dic, imod2$dic$dic)
```
```{r}
c(imod$waic$waic, imod1$waic$waic, imod2$waic$waic)
```
```{r}
exp(imod1$summary.fixed[-1, c(3,4,5)])
```
```{r}
ohio$obst = rep(1:4,537)
ohio$repl = ohio$id + 1
formula <- resp ~ factor(age) + smoke + f(obst, model="ar1", replicate = repl)
imod <- inla(formula, family="binomial", data=ohio)
```
```{r}
exp(imod$summary.fixed[-1, c(3,4,5)])
```
```{r}
bri.hyperpar.summary(imod)
```
```{r}
sessionInfo()
```
