---
title: "Introduction to INLA"
author: "Julian Faraway"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to INLA}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
data(hubble, package="brinla")
```
```{r}
plot(y ~ x, xlab="Distance(Mpc)", ylab="Velocity(km/s)", data=hubble)
```
```{r}
lmod <- lm(y~x-1, data=hubble)
coef(lmod)
```
```{r}
hubtoage <- function(x) 3.09e19/(x*60^2*24*365.25*1e9)
hubtoage(coef(lmod))
```
```{r}
(bci <- confint(lmod))
```
```{r}
hubtoage(bci)
```
```{r}
library(INLA)
```
```{r}
imod <- inla(y ~ x -1, family="gaussian", control.fixed = list(prec = 1e-9), data=hubble)
```
```{r}
(ibci <- imod$summary.fixed)
```
```{r}
x <- seq(60,100,length.out = 100)
plot(imod$marginals.fixed$x, type="l", xlab="beta", ylab="density", xlim=c(60,100))
abline(v=ibci[c(3,5)],lty=2)
```
```{r}
hubtoage(ibci[c(1,3,4,5,6)])
```
```{r}
ageden <- inla.tmarginal(hubtoage,imod$marginals.fixed$x)
plot(ageden,type="l",xlab="Age in billions of years",ylab="density")
abline(v=hubtoage(ibci[c(3,5)]),lty=2)
```
```{r}
hubtoage(c(10,15,20))
```
```{r}
imod <- inla(y ~ x -1, family="gaussian", control.fixed=list(mean=65, prec=1/(12^2)), data=hubble)
(ibci <- imod$summary.fixed)
```
```{r}
hubtoage(ibci[c(1,3,4,5,6)])
```
```{r}
(uhub <- hubtoage((2016+4004-1)/1e9))
```
```{r}
imod <- inla(y ~ x -1, family="gaussian", control.fixed=list(mean=uhub, prec=1/((0.05*uhub)^2)), data=hubble)
(ibci <- imod$summary.fixed)
```
```{r}
hubtoage(ibci[c(1,3,4,5,6)])
```

